adaptive_tracking: false
dist_scale_coeff: 5.0
max_lost_duration: 1.0
min_detect_count: 5
odom_frame: odom
q_geo: 0.0001
q_v_yaw: 0.01
q_vx: 0.1
q_vy: 0.01
q_vz: 0.1
q_x: 0.1
q_y: 0.1
q_yaw: 0.01
q_z: 0.001
q_alpha: 0.1
r_x: 0.5
r_y: 0.5
r_yaw: 5.0
r_yaw_adaptive_factor: 50.0
r_z: 0.5
ukf_alpha: 0.001
ukf_beta: 2.0
ukf_kappa: 0.0
use_sim_time: false
z_scale_coeff: 10.0
